language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

install:
  - composer require --dev phpstan/phpstan:^0.12

before_script: composer install

script:
  - ./bin/php-cs-fixer fix lib/ --dry-run --diff
  - ./bin/phpstan.phar analyse -c phpstan.neon lib
  - ./bin/phpunit --configuration tests/phpunit.xml
