language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm


script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/sabre-cs-fixer fix lib/ --dry-run --diff

before_script: composer install
